const { DataTypes } = require("sequelize");
module.exports = (sequelize) =>
  sequelize.define(
    "ParentsFiche",
    {
      id: {
        type: DataTypes.INTEGER.UNSIGNED,
        autoIncrement: true,
        primaryKey: true,
      },
      enfant_id: {
        type: DataTypes.INTEGER.UNSIGNED,
        allowNull: false,
        unique: true,
      },
      // pere_user_id: DataTypes.INTEGER.UNSIGNED,
      pere_nom: DataTypes.STRING(100),
      pere_prenom: DataTypes.STRING(100),
      pere_naissance_date: DataTypes.DATEONLY,
      pere_naissance_lieu: DataTypes.STRING(150),
      pere_origine: DataTypes.STRING(150),
      pere_cin_numero: DataTypes.STRING(50),
      pere_cin_delivree_a: DataTypes.STRING(150),
      pere_adresse: DataTypes.STRING(255),
      pere_profession: DataTypes.STRING(120),
      pere_couverture_sociale: DataTypes.STRING(255),
      pere_tel_domicile: DataTypes.STRING(50),
      pere_tel_travail: DataTypes.STRING(50),
      pere_tel_portable: DataTypes.STRING(50),
      // mere_user_id: DataTypes.INTEGER.UNSIGNED,
      mere_nom: DataTypes.STRING(100),
      mere_prenom: DataTypes.STRING(100),
      mere_naissance_date: DataTypes.DATEONLY,
      mere_naissance_lieu: DataTypes.STRING(150),
      mere_origine: DataTypes.STRING(150),
      mere_cin_numero: DataTypes.STRING(50),
      mere_cin_delivree_a: DataTypes.STRING(150),
      mere_adresse: DataTypes.STRING(255),
      mere_profession: DataTypes.STRING(120),
      mere_couverture_sociale: DataTypes.STRING(255),
      mere_tel_domicile: DataTypes.STRING(50),
      mere_tel_travail: DataTypes.STRING(50),
      mere_tel_portable: DataTypes.STRING(50),
    },
    { tableName: "parents_fiche", underscored: true, timestamps: true }
  );
